Metrics:
  Enabled: false

# Change style to match rufo
Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

# Prefer compact module/class defs
Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/AlignParameters:
  Enabled: false
  
Naming/AccessorMethodName:
  Exclude:
    - lib/rapture/rest.rb
    - lib/rapture/rest/*
    

# Allow CamelCase constants as well as SCREAMING_SNAKE_CASE
Naming/ConstantName:
  Enabled: false

# Allow 'Pokémon-style' exception handling
Lint/RescueException:
  Enabled: false

# Prefer |m, e| for the `reduce` block arguments
Style/SingleLineBlockParams:
  Methods:
    - reduce: [m, e]
    - inject: [m, e]

AllCops:
  TargetRubyVersion: 2.4

# http://stackoverflow.com/questions/4763121/should-i-use-alias-or-alias-method
Style/Alias:
  Enabled: false
