version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - run:
          name: Installer Bundler
          command: gem install bundler -v 2.0.2
      - restore_cache:
          keys:
            - rapture-cache-
      - run:
          name: Install Dependencies
          command: bundle check --path vendor/bundle || bundle install
      - save_cache:
          key: rapture-cache-
          paths:
            - vendor/bundle      
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run Tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rake test
            ./cc-test-reporter after-build -t simplecov --exit-code $?
      - store_test_results:
          path: test/reports
      - run:
          name: Formatting Check
          command: bundle exec rake format
      - run:
          name: Doc Test
          command: bundle exec yard doc
  docs-build:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler -v 2.0.2
      - restore_cache:
          keys:
            - rapture-cache-
      - run:
          name: Install dependencies
          command: bundle check --path vendor/bundle || bundle install 
      - save_cache:
          key: rapture-cache-
          paths:
            - vendor/bundle
      - run:
          name: Build docs
          command: bundle exec yard
      - persist_to_workspace:
          root: .
          paths:
            - doc/
  
  docs-deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - rapture-docs-deploy-cache-
      - run:
          name: Install dependencies
          command: |
            npm config set prefix .node
            npm install -g gh-pages@2.0.1
      - save_cache:
          key: rapture-docs-deploy-cache-
          paths:
            - .node
      - run:
          name: Configure Dependencies
          command: |
            git config user.email "ci-build@swarley.xyz"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "7e:f7:e3:9c:be:14:cc:cb:e1:83:bd:72:a1:b0:c5:de"
      - run:
          name: Deploy to gh-pages
          command: .node/bin/gh-pages --message "[skip ci] Updates" --dist doc

workflows:
  version: 2
  build:
    jobs:
      - test
      - docs-build
      - docs-deploy:
          requires:
            - test
            - docs-build
          filters:
            branches:
              only: master