version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - run:
          name: Installer Bundler
          command: gem install bundler -v 2.0.2
      
      - run:
          name: Install Dependencies
          command: bundle check --path vendor/bundle || bundle install
      
      - run:
          name: Run Tests
          command: bundle exec rake test
      
      - run:
          name: Formatting Check
          command: bundle exec rake format
