version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
        environment:
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - run:
          name: Installer Bundler
          command: gem install bundler -v 2.0.2
      
      - run:
          name: Install Dependencies
          command: bundle check --path vendor/bundle || bundle install
      
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            
      - run:
          name: Run Tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rake test
            ./cc-test-reporter after-build -t simplecov --exit-code $?

      - store_test_results:
          path: test/reports

      - run:
          name: Formatting Check
          command: bundle exec rake format
